// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzwjnuiytqjriyoxcuko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6d2pudWl5dHFqcml5b3hjdWtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5OTM4MzQsImV4cCI6MjA5MDU2OTgzNH0.KD3IThIqlhb4l-FBQE6EZpe22dCNoXEVBiA_03aZSrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});